server:
  port: 8090
spring:
  application:
    name: smmpoc
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/auth/realms/smm-poc-approach
          jwk-set-uri: http://localhost:8083/auth/realms/smm-poc-approach/protocol/openid-connect/certs

