server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystores/smmpoc.p12
    key-store-password: password
    key-alias: smmpoc
    enabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  application:
    name: smmpoc
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost/realms/smm-poc-approach

